[package]
name = "og"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = "2.33.3"
tar = "0.4.37"
flate2 = "1.0.22"
home = "0.5.3"
serde_json = "1.0.59"
futures-util = "0.3.17"
indicatif = "0.16.2"
reqwest =  { version = "0.11.5", features = ["stream"] }
tokio = { version = "1.12.0", features = ["full"] }
