[package]
name = "opengame"
version = "0.0.1"
edition = "2018"

[dependencies]
clap = "2.33.3"
async-trait = "0.1.52"
tar = "0.4.37"
flate2 = "1.0.22"
serde_json = "1.0.59"
futures-util = "0.3.17"
indicatif = "0.16.2"

[dependencies.reqwest]
version = "0.11.5"
features = ["stream"]

[dependencies.tokio]
version = "1.12.0"
features = ["full"]
