[package]
name = "opengame"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = "2.34.0"
async-trait = "0.1.52"
tar = "0.4.38"
serde_json = "1.0.73"
futures-util = "0.3.19"
indicatif = "0.16.2"

[dependencies.reqwest]
version = "0.11.8"
default-features = false
features = ["rustls-tls", "stream"]

[dependencies.tokio]
version = "1.15.0"
features = ["full"]
