[package]
name = "og"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = "2.33.3"
flate2 = "1.0.22"
dirs = "4.0.0"
serde_json = "1.0.59"
reqwest = "0.11.5"
tokio = { version = "1.12.0", features = ["full"] }
