name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cross:
    runs-on: ubuntu-latest
    
    steps:
      - name: Installation
        run: cargo install cross

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
 
  build:
    needs: [cross]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - i686-unknown-linux-gnu
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cross build --target ${{ matrix.target }} --release --verbose
